import { Router } from "express";
import authRoutes from "./authRoutes.js";
import facilityRoutes from "./facilityRoutes.js";
import eventRoutes from "./eventRoutes.js";
import noticeRoutes from "./noticeRoutes.js";
import pushRoutes from "./pushRoutes.js";
import timetableRoutes from "./timetableRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import groupRoutes from "./groupRoutes.js";
import assignmentRoutes from "./assignmentRoutes.js";
import hodSubmissionRoutes from "./hodSubmissionRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import attendanceRoutes from "./attendanceRoutes.js";
import eventRegistrationRoutes from "./eventRegistrationRoutes.js";
import userRoutes from "./userRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import aiRoutes from "./aiRoutes.js";
import aiVisionRoutes from "./aiVisionRoutes.js";
import auditLogRoutes from "./auditLogRoutes.js";
import lockRoutes from "./lockRoutes.js";

const router = Router();
router.get("/health", (req, res) => res.json({ success: true, message: "API healthy" }));
router.use("/auth", authRoutes);
router.use("/facilities", facilityRoutes);
router.use("/events", eventRoutes);
router.use("/notices", noticeRoutes);
router.use("/push", pushRoutes);
router.use("/timetables", timetableRoutes);
router.use("/upload", uploadRoutes);
router.use("/uploads", uploadRoutes);
router.use("/groups", groupRoutes);
router.use("/assignments", assignmentRoutes);
router.use("/hod-submissions", hodSubmissionRoutes);
router.use("/notifications", notificationRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/event-registrations", eventRegistrationRoutes);
router.use("/users", userRoutes);
router.use("/payments", paymentRoutes);
router.use("/ai", aiRoutes);
router.use("/ai", aiVisionRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/admin/locks", lockRoutes);
export default router;
